#
# Makefile for the touchscreen drivers.
#

# Each configuration option enables a list of files.
obj-$(CONFIG_TOUCHSCREEN_MELFAS_I2C_TSI_COMBO)	+= melfas_i2c_tsi.o
obj-$(CONFIG_TOUCHSCREEN_MELFAS_I2C_TSI_COMBO)	+= melfas_download.o
obj-$(CONFIG_TOUCHSCREEN_MELFAS_I2C_TSI_COMBO)	+= melfas_downloadmcs5000.o

